services:
  db:
    image: postgres:15
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filemanagement

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      -  ./backend/.env        

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
